settings:
  rule: "-"
  ruleRepetition: 3
  ruleSpaces: false

  bullet: "-"

plugins:
  - remark-parse
  - - remark-frontmatter
    - type: yaml
      marker: "-"
  - - remark-gfm
    - tablePipeAlign: false
  - remark-lint
  - - ./tools/docs/src/remark-md-content.cjs
    - schemas:
        docs/specdojo/schemas/v1/pjr-index.schema.yaml:
          - docs/ja/**/pjr-index.md
  - - ./tools/docs/src/remark-frontmatter-ajv2020.cjs
    - strict: true
      schemaRules: # 配列なので上から順に評価し、最初にマッチしたスキーマを適用します。
        - glob: docs/ja/projects/**/exec/plans/**/*.md
          schema: docs/specdojo/schemas/v1/exec-plan-frontmatter.schema.yaml
        - glob: docs/ja/projects/**/exec/results/**/*.md
          schema: docs/specdojo/schemas/v1/exec-result-frontmatter.schema.yaml
        - glob: docs/ja/projects/**/exec/results/**/*.md
          schema: docs/specdojo/schemas/v1/exec-result-frontmatter.schema.yaml
        - glob: docs/ja/specdojo/rulebooks/**/*.md
          schema: docs/specdojo/schemas/v1/rulebook-frontmatter.schema.yaml
        - glob: docs/ja/specdojo/guidelines/**/*.md
          schema: docs/specdojo/schemas/v1/guide-frontmatter.schema.yaml
        - glob: docs/ja/specdojo/standards/**/*.md
          schema: docs/specdojo/schemas/v1/standard-frontmatter.schema.yaml
        - glob: docs/ja/specdojo/recipes/**/*.md
          schema: docs/specdojo/schemas/v1/recipe-frontmatter.schema.yaml
        - glob: docs/ja/product/**/*.md
          schema: docs/specdojo/schemas/v1/deliverable-frontmatter.schema.yaml
        - glob: docs/ja/projects/**/*.md
          schema: docs/specdojo/schemas/v1/deliverable-frontmatter.schema.yaml
        - glob: docs/ja/specdojo/samples/**/*.md
          schema: docs/specdojo/schemas/v1/deliverable-frontmatter.schema.yaml
