import { type Command } from "commander";
import { dirname, join, relative, resolve } from "node:path";
import { existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import yaml from "js-yaml";
import {
  getProjectCatalogPath,
  getProjectRolesPath,
  getProjectSchedulePath,
  getProjectTimelinePath,
  loadConfig,
  loadEnv,
  specdojoRootDir,
} from "./specdojo-config.js";
import {
  buildScheduleTrack,
  type BuildResult,
  type GeneratedMilestone,
  type GeneratedTask,
} from "./schedule-build.js";
import { readYaml } from "./exec-shared.js";
import {
  assessmentFileName,
  buildAssessmentSkeleton,
  collectAssessmentFacts,
  loadAssessment,
  loadStrategyScope,
  resolveAssessmentPath,
  resolveAssessmentsDir,
  SCH_ASSESSMENT_SCHEMA_PATH,
  validateAssessment,
  validateAssessmentSchema,
  writeAssessment,
  type AssessedDeliverable,
  type AssessmentFacts,
  type SchAssessment,
} from "./schedule-assessment.js";
import { renderAssessmentPrompt } from "./schedule-assessment-prompt.js";
import {
  generateStrategyFromAssessment,
  resolveTrackScopeCatalogs,
  strategyPathFor,
  writeStrategyFile,
} from "./schedule-strategy-generate.js";

type ResolvedScheduleContext = {
  schedulePath: string;
  baseDir: string;
  projectId: string;
  catalogPath: string | null;
  timelinePath: string;
  rolesPath?: string;
};

function resolveSchedulePath(opts: { project?: string }): ResolvedScheduleContext {
  loadEnv();
  const { config, configPath } = loadConfig();
  const baseDir = specdojoRootDir();

  const projectId =
    opts.project?.trim() ||
    process.env.SPECDOJO_PROJECT?.trim() ||
    (config ? Object.keys(config.projects)[0] : "");

  if (!config) {
    throw new Error(`schedule commands require specdojo.config.json.\nRun: specdojo config init`);
  }
  if (!projectId) {
    throw new Error(`No project specified. Use --project <id> or SPECDOJO_PROJECT.`);
  }

  const project = config.projects[projectId];
  if (!project) {
    throw new Error(`Unknown project: ${projectId} (check ${configPath})`);
  }

  if (!project.schedule_path?.trim()) {
    throw new Error(`schedule_path not set for project '${projectId}' in ${configPath}.`);
  }

  const catalogPath = getProjectCatalogPath(project);
  const rolesPath = getProjectRolesPath(project);
  return {
    schedulePath: resolve(baseDir, getProjectSchedulePath(project)),
    baseDir,
    projectId,
    catalogPath: catalogPath ? resolve(baseDir, catalogPath) : null,
    timelinePath: resolve(baseDir, getProjectTimelinePath(project)),
    ...(rolesPath ? { rolesPath } : {}),
  };
}

export type ProjectMilestoneBuild = {
  milestones: GeneratedMilestone[];
  errors: string[];
  warnings: string[];
};

export function collectProjectMilestones(
  schedulePath: string,
  baseDir: string,
  projectId: string,
  prebuilt?: { strategyPath: string; result: BuildResult },
): ProjectMilestoneBuild {
  const milestones: GeneratedMilestone[] = [];
  const errors: string[] = [];
  const warnings: string[] = [];
  const owners = new Map<string, string>();
  const prebuiltPath = prebuilt ? resolve(prebuilt.strategyPath) : undefined;
  const strategyFiles = readdirSync(schedulePath)
    .filter((file) => /^sch-strategy-.+\.yaml$/.test(file))
    .sort();

  for (const file of strategyFiles) {
    const strategyPath = join(schedulePath, file);
    let result: BuildResult;
    try {
      result =
        prebuilt && prebuiltPath === resolve(strategyPath)
          ? prebuilt.result
          : buildScheduleTrack(strategyPath, baseDir);
    } catch (error) {
      errors.push(`${file}: ${error instanceof Error ? error.message : String(error)}`);
      continue;
    }

    warnings.push(...result.warnings.map((warning) => `${file}: ${warning}`));
    errors.push(...result.errors.map((error) => `${file}: ${error}`));
    if (result.errors.length > 0) continue;
    if (result.projectId !== projectId) {
      errors.push(
        `${file}: project id '${result.projectId}' does not match requested project '${projectId}'`,
      );
      continue;
    }

    for (const milestone of result.milestones) {
      const previousOwner = owners.get(milestone.id);
      if (previousOwner) {
        errors.push(
          `Duplicate milestone ID '${milestone.id}' generated by ${previousOwner} and ${file}`,
        );
        continue;
      }
      owners.set(milestone.id, file);
      milestones.push(milestone);
    }
  }

  return { milestones, errors, warnings };
}

export function updateMilestonesFile(
  schedulePath: string,
  projectId: string,
  newMilestones: GeneratedMilestone[],
  dryRun: boolean,
): { added: string[]; updated: string[]; removed: string[]; fileCreated: boolean } {
  const filePath = join(schedulePath, "sch-milestones.yaml");
  if (newMilestones.length === 0 && !existsSync(filePath))
    return { added: [], updated: [], removed: [], fileCreated: false };

  const added: string[] = [];
  const updated: string[] = [];
  let fileCreated = false;

  let doc: Record<string, unknown>;

  if (existsSync(filePath)) {
    const parsed = readYaml(filePath);
    if (!parsed || typeof parsed !== "object") {
      throw new Error(`${filePath}: invalid or empty YAML`);
    }
    doc = parsed as Record<string, unknown>;
    if (!Array.isArray(doc.milestones)) doc.milestones = [];
    // Status is human-managed after creation; rebuilding generated content must preserve it.
  } else {
    doc = {
      kind: "milestones",
      id: `${projectId}:sch-milestones`,
      type: "project",
      status: "draft",
      version: 1,
      project_id: projectId,
      settings: {},
      milestones: [],
    };
    fileCreated = true;
  }

  const previous = doc.milestones as Array<Record<string, unknown>>;
  const previousIds = new Set(previous.map((entry) => String(entry?.id ?? "")));
  const newIds = new Set(newMilestones.map((m) => m.id));
  const removed: string[] = [];
  for (const entry of previous) {
    const id = String(entry?.id ?? "");
    if (!newIds.has(id)) removed.push(id);
  }

  for (const m of newMilestones) {
    if (previousIds.has(m.id)) updated.push(m.id);
    else added.push(m.id);
  }

  // Keep the established presentation order for milestones that still exist, while replacing
  // every field from the freshly generated definitions. Newly generated IDs are appended in the
  // deterministic all-strategy order so adding a track does not move existing track sections.
  const generatedById = new Map(newMilestones.map((milestone) => [milestone.id, milestone]));
  const orderedMilestones: GeneratedMilestone[] = [];
  for (const entry of previous) {
    const id = String(entry?.id ?? "");
    const generated = generatedById.get(id);
    if (!generated) continue;
    orderedMilestones.push(generated);
    generatedById.delete(id);
  }
  for (const milestone of newMilestones) {
    if (!generatedById.has(milestone.id)) continue;
    orderedMilestones.push(milestone);
    generatedById.delete(milestone.id);
  }
  doc.milestones = orderedMilestones.map((milestone) => ({ ...milestone }));

  const outYaml = yaml.dump(doc, { lineWidth: 120, noRefs: true });

  if (dryRun) {
    const label = fileCreated ? "created" : "updated";
    process.stdout.write(`\n# --- (dry-run) sch-milestones.yaml (${label}) ---\n`);
    process.stdout.write(outYaml);
  } else {
    writeFileSync(filePath, outYaml, "utf8");
  }

  return { added, updated, removed, fileCreated };
}

function printCommandError(error: unknown): void {
  const message = error instanceof Error ? error.message : String(error);
  process.stdout.write(message + "\n");
  process.exitCode = 1;
}

function addProjectOption(cmd: Command): Command {
  return cmd.option("--project <projectId>", "Project id in specdojo.config.json");
}

export function createScheduleTrackDocument(input: {
  projectId: string;
  track: string;
  status: string;
  startDate: string | null;
  tasks: GeneratedTask[];
}): Record<string, unknown> {
  return {
    kind: "track",
    id: `${input.projectId}:sch-track-${input.track}`,
    type: "project",
    status: input.status,
    title: `スケジュールトラック（${input.track}）`,
    rulebook: "specdojo:sch-rulebook",
    version: 1,
    project_id: input.projectId,
    track: input.track,
    settings: input.startDate !== null ? { start_date: input.startDate } : {},
    tasks: input.tasks,
  };
}

function repoRelative(absolutePath: string): string {
  return relative(specdojoRootDir(), absolutePath).replace(/\\/g, "/");
}

function requireTrack(track: unknown): string {
  const value = typeof track === "string" ? track.trim() : "";
  if (!value) {
    throw new Error(`--track <track> is required (e.g. --track launch).`);
  }
  return value;
}

function printDiff(diff: string[]): void {
  const MAX_DIFF_LINES = 200;
  for (const line of diff.slice(0, MAX_DIFF_LINES)) {
    process.stdout.write(`${line}\n`);
  }
  if (diff.length > MAX_DIFF_LINES) {
    process.stdout.write(`... (${diff.length - MAX_DIFF_LINES} more diff lines)\n`);
  }
}

// Schema + semantic validation for one assessment. Returns false when the assessment must not
// be written or accepted.
function reportAssessmentValidation(
  assessment: SchAssessment,
  opts: { fileName: string; currentFacts?: Map<string, AssessmentFacts> },
): boolean {
  const schemaErrors = validateAssessmentSchema(assessment, specdojoRootDir());
  for (const err of schemaErrors) {
    process.stdout.write(`ERROR: ${opts.fileName}${err}\n`);
  }
  if (schemaErrors.length > 0) return false;

  const result = validateAssessment(assessment, {
    fileName: opts.fileName,
    ...(opts.currentFacts ? { currentFacts: opts.currentFacts } : {}),
  });
  for (const err of result.errors) process.stdout.write(`ERROR: ${err}\n`);
  for (const warn of result.warnings) process.stdout.write(`WARN:  ${warn}\n`);
  return result.ok;
}

type CollectedScope = {
  strategyPath: string;
  scope: ReturnType<typeof loadStrategyScope>;
  deliverables: AssessedDeliverable[];
  factsByLocalId: Map<string, AssessmentFacts>;
};

// Collects the machine-determined facts for a track. Errors here mean the scope itself cannot be
// resolved, so no agent judgment should be attempted.
function collectScope(context: ResolvedScheduleContext, track: string): CollectedScope {
  const repoRoot = specdojoRootDir();
  const strategyPath = strategyPathFor(context.schedulePath, track);
  let scope: ReturnType<typeof loadStrategyScope>;
  if (existsSync(strategyPath)) {
    scope = loadStrategyScope(strategyPath);
  } else {
    if (!existsSync(join(context.timelinePath, "tml-index.yaml"))) {
      throw new Error(`Strategy file not found: ${strategyPath}`);
    }
    if (!context.catalogPath) {
      throw new Error(`catalog_path is required to resolve track '${track}' from Timeline.`);
    }
    const resolved = resolveTrackScopeCatalogs({
      repoRoot,
      catalogPath: context.catalogPath,
      timelinePath: context.timelinePath,
      track,
      existingStrategy: null,
    });
    for (const warning of resolved.warnings) process.stdout.write(`WARN:  ${warning}\n`);
    if (resolved.errors.length > 0) throw new Error(resolved.errors.join("\n"));
    scope = {
      strategyId: `${context.projectId}:sch-strategy-${track}`,
      track,
      projectId: context.projectId,
      catalogs: resolved.catalogs.map((catalog) => ({ id: catalog.id, path: catalog.path })),
      includeKinds: ["work"],
    };
  }
  if (scope.track !== track) {
    throw new Error(
      `${repoRelative(strategyPath)}: track '${scope.track}' does not match '${track}'.`,
    );
  }
  const collected = collectAssessmentFacts({ repoRoot, scope });
  for (const warning of collected.warnings) process.stdout.write(`WARN:  ${warning}\n`);
  if (collected.errors.length > 0) {
    throw new Error(collected.errors.join("\n"));
  }
  return {
    strategyPath,
    scope,
    deliverables: collected.deliverables,
    factsByLocalId: new Map(collected.deliverables.map((item) => [item.local_id, item.facts])),
  };
}

// `schedule assessment` handles the agent judgment artifact (sch-assessment-<track>.yaml) that
// sits between the deliverable catalogs and the deterministic strategy generator.
function registerScheduleAssessmentCommands(sch: Command): void {
  const assessment = sch
    .command("assessment")
    .description("Readiness assessment (sch-assessment-<track>.yaml) commands for agent judgment");

  const aScaffold = assessment
    .command("scaffold")
    .description(
      "Create sch-assessment-<track>.yaml (facts only, or ingest agent output with --from)",
    );
  addProjectOption(aScaffold);
  aScaffold.requiredOption("--track <track>", "Track name (e.g. launch)");
  aScaffold.option("--from <path>", "Agent-produced assessment file to validate and store");
  aScaffold.option("--force", "Overwrite an existing assessment", false);
  aScaffold.option("--dry-run", "Show the diff without writing", false);
  aScaffold.action((opts) => {
    try {
      const context = resolveSchedulePath(opts);
      const { schedulePath } = context;
      const track = requireTrack(opts.track);
      const collected = collectScope(context, track);

      let doc: SchAssessment;
      if (opts.from) {
        const fromPath = resolve(specdojoRootDir(), opts.from as string);
        if (!existsSync(fromPath)) {
          throw new Error(`--from not found: ${opts.from}`);
        }
        doc = loadAssessment(fromPath);
        if (doc.track !== track) {
          throw new Error(
            `--from assessment track '${doc.track}' does not match --track '${track}'.`,
          );
        }
      } else {
        doc = buildAssessmentSkeleton({
          scope: collected.scope,
          strategyRelPath: repoRelative(collected.strategyPath),
          deliverables: collected.deliverables,
        });
      }

      const ok = reportAssessmentValidation(doc, {
        fileName: assessmentFileName(track),
        currentFacts: collected.factsByLocalId,
      });
      if (!ok) {
        process.exitCode = 1;
        return;
      }

      const result = writeAssessment({
        schedulePath,
        assessment: doc,
        force: !!opts.force,
        dryRun: !!opts.dryRun,
      });

      if (result.written) {
        process.stdout.write(`${opts.force ? "Updated" : "Created"}: ${result.path}\n`);
        return;
      }
      if (result.skippedReason === "unchanged") {
        process.stdout.write(`Unchanged: ${result.path}\n`);
        return;
      }
      if (result.skippedReason === "dry-run") {
        process.stdout.write(`Dry-run (not written): ${result.path}\n`);
        printDiff(result.diff);
        return;
      }
      process.stdout.write(
        `Skipped (already exists; use --force to overwrite): ${result.path}\n` +
          `Review the diff below before overwriting.\n`,
      );
      printDiff(result.diff);
    } catch (error) {
      printCommandError(error);
    }
  });

  const aPrompt = assessment
    .command("prompt")
    .description("Print the agent instruction for judging deliverable and Kata readiness");
  addProjectOption(aPrompt);
  aPrompt.requiredOption("--track <track>", "Track name (e.g. launch)");
  aPrompt.option("--out <path>", "Write the instruction to a file instead of stdout");
  aPrompt.action((opts) => {
    try {
      const context = resolveSchedulePath(opts);
      const { schedulePath } = context;
      const track = requireTrack(opts.track);
      const collected = collectScope(context, track);
      const assessmentPath = resolveAssessmentPath(schedulePath, track);

      const prompt = renderAssessmentPrompt({
        projectId: collected.scope.projectId,
        track,
        strategyRelPath: repoRelative(collected.strategyPath),
        assessmentRelPath: repoRelative(assessmentPath),
        schemaRelPath: SCH_ASSESSMENT_SCHEMA_PATH,
        deliverables: collected.deliverables,
        assessmentExists: existsSync(assessmentPath),
      });

      if (opts.out) {
        const outPath = resolve(specdojoRootDir(), opts.out as string);
        mkdirSync(dirname(outPath), { recursive: true });
        writeFileSync(outPath, prompt, "utf8");
        process.stdout.write(`Created: ${outPath}\n`);
        return;
      }
      process.stdout.write(prompt);
    } catch (error) {
      printCommandError(error);
    }
  });

  const aValidate = assessment
    .command("validate")
    .description("Validate sch-assessment-*.yaml files");
  addProjectOption(aValidate);
  aValidate.option("--track <track>", "Limit validation to one track");
  aValidate.action((opts) => {
    try {
      const context = resolveSchedulePath(opts);
      const { schedulePath } = context;
      const assessmentsDir = resolveAssessmentsDir(schedulePath);
      const track = typeof opts.track === "string" ? opts.track.trim() : "";
      const files = (existsSync(assessmentsDir) ? readdirSync(assessmentsDir) : [])
        .filter((file) => /^sch-assessment-.+\.yaml$/.test(file))
        .filter((file) => !track || file === assessmentFileName(track))
        .sort();

      if (files.length === 0) {
        process.stdout.write(
          track
            ? `No ${assessmentFileName(track)} found in: ${assessmentsDir}\n`
            : `No sch-assessment-*.yaml files found in: ${assessmentsDir}\n`,
        );
        return;
      }

      let allOk = true;
      for (const file of files) {
        const filePath = join(assessmentsDir, file);
        try {
          const doc = loadAssessment(filePath);
          const collected = collectScope(context, doc.track);
          const ok = reportAssessmentValidation(doc, {
            fileName: file,
            currentFacts: collected.factsByLocalId,
          });
          if (ok) {
            process.stdout.write(`OK: ${file}\n`);
          } else {
            allOk = false;
          }
        } catch (error) {
          process.stdout.write(
            `ERROR: ${filePath}: ${error instanceof Error ? error.message : String(error)}\n`,
          );
          allOk = false;
        }
      }
      if (!allOk) process.exitCode = 1;
    } catch (error) {
      printCommandError(error);
    }
  });
}

function collectRepeatable(value: string, previous: string[] = []): string[] {
  return [...previous, value];
}

function parseOwnerOverrides(values: string[]): Map<string, string> {
  const owners = new Map<string, string>();
  for (const value of values) {
    const separator = value.indexOf("=");
    const localId = separator >= 0 ? value.slice(0, separator).trim() : "";
    const owner = separator >= 0 ? value.slice(separator + 1).trim() : "";
    if (!localId || !owner) {
      throw new Error(`Invalid --owner '${value}'. Expected <local_id>=<ROLE>.`);
    }
    const previous = owners.get(localId);
    if (previous && previous !== owner) {
      throw new Error(`Conflicting --owner values for '${localId}': '${previous}' and '${owner}'.`);
    }
    owners.set(localId, owner);
  }
  return owners;
}

// `schedule strategy generate` is the only path that turns an assessment into strategy YAML.
// The generator performs schema, scope, owner, dependency and schedule dry-run validation before
// this command is allowed to replace a file.
function registerScheduleStrategyCommands(sch: Command): void {
  const strategy = sch
    .command("strategy")
    .description("Deterministic sch-strategy-<track>.yaml generation commands");
  const generate = strategy
    .command("generate")
    .description("Generate sch-strategy-<track>.yaml from DCT, Timeline and assessment");
  addProjectOption(generate);
  generate.requiredOption("--track <track>", "Track name (e.g. launch)");
  generate.option(
    "--owner <local_id=role>",
    "Owner override for one deliverable (repeatable)",
    collectRepeatable,
    [] as string[],
  );
  generate.option("--default-owner <role>", "Fallback owner for unresolved deliverables");
  generate.option("--gate-owner <role>", "Owner of generated phase gates");
  generate.option("--milestone-owner <role>", "Owner of generated group milestones");
  generate.option("--pass-owner <role>", "Owner of a generated cross-deliverable pass");
  generate.option(
    "--no-bootstrap-ordering",
    "Do not make non-bootstrap deliverables wait for representative bootstrap deliverables",
  );
  generate.option(
    "--force",
    "Overwrite an existing strategy after showing a reviewable diff",
    false,
  );
  generate.option("--dry-run", "Validate and show the diff without writing", false);
  generate.action((opts) => {
    try {
      const context = resolveSchedulePath(opts);
      const track = requireTrack(opts.track);
      if (!context.catalogPath) {
        throw new Error(`catalog_path not set for project '${context.projectId}'.`);
      }
      const assessmentPath = resolveAssessmentPath(context.schedulePath, track);
      if (!existsSync(assessmentPath)) {
        throw new Error(
          `Assessment file not found: ${assessmentPath}\n` +
            `Run: specdojo schedule assessment scaffold --track ${track}`,
        );
      }
      const assessment = loadAssessment(assessmentPath);
      const result = generateStrategyFromAssessment({
        repoRoot: context.baseDir,
        schedulePath: context.schedulePath,
        catalogPath: context.catalogPath,
        timelinePath: context.timelinePath,
        ...(context.rolesPath ? { rolesPath: context.rolesPath } : {}),
        projectId: context.projectId,
        track,
        assessment,
        ownerOverrides: parseOwnerOverrides(opts.owner as string[]),
        ...(typeof opts.defaultOwner === "string"
          ? { defaultOwner: opts.defaultOwner.trim() }
          : {}),
        ...(typeof opts.gateOwner === "string" ? { gateOwner: opts.gateOwner.trim() } : {}),
        ...(typeof opts.milestoneOwner === "string"
          ? { milestoneOwner: opts.milestoneOwner.trim() }
          : {}),
        ...(typeof opts.passOwner === "string" ? { passOwnerOverride: opts.passOwner.trim() } : {}),
        bootstrapOrdering: opts.bootstrapOrdering !== false,
      });
      for (const warning of result.warnings) process.stdout.write(`WARN:  ${warning}\n`);
      for (const error of result.errors) process.stdout.write(`ERROR: ${error}\n`);
      if (result.errors.length > 0 || !result.doc) {
        process.stdout.write(`Not written (${track}): validation failed.\n`);
        process.exitCode = 1;
        return;
      }

      const written = writeStrategyFile({
        schedulePath: context.schedulePath,
        track,
        content: result.content,
        force: !!opts.force,
        dryRun: !!opts.dryRun,
      });
      const summary = `${result.taskCount} tasks, ${result.milestoneIds.length} milestones`;
      if (written.written) {
        process.stdout.write(
          `${opts.force ? "Updated" : "Created"}: ${written.path} (${summary})\n`,
        );
        return;
      }
      if (written.skippedReason === "unchanged") {
        process.stdout.write(`Unchanged: ${written.path} (${summary})\n`);
        return;
      }
      if (written.skippedReason === "dry-run") {
        process.stdout.write(`Dry-run (not written): ${written.path} (${summary})\n`);
        printDiff(written.diff);
        return;
      }
      process.stdout.write(
        `Skipped (already exists; use --force to overwrite): ${written.path}\n` +
          `Review the diff below before overwriting.\n`,
      );
      printDiff(written.diff);
    } catch (error) {
      printCommandError(error);
    }
  });
}

export function registerScheduleCommands(program: Command): void {
  const sch = program.command("schedule").description("Schedule build commands");

  // --- where ---
  const wcmd = sch.command("where").description("Print resolved schedule paths and file list");
  addProjectOption(wcmd);
  wcmd.action((opts) => {
    try {
      const { schedulePath } = resolveSchedulePath(opts);
      process.stdout.write(`schedule-path: ${schedulePath}\n`);

      if (!existsSync(schedulePath)) {
        process.stdout.write(`(path does not exist)\n`);
        return;
      }

      const files = readdirSync(schedulePath)
        .filter((f) => /^sch-.+\.yaml$/.test(f))
        .sort();
      const strategyFiles = files.filter((f) => f.startsWith("sch-strategy-"));
      const trackFiles = files.filter((f) => f.startsWith("sch-track-"));

      process.stdout.write(`strategy-files:\n`);
      if (strategyFiles.length === 0) {
        process.stdout.write(`  (none)\n`);
      } else {
        for (const f of strategyFiles) process.stdout.write(`  - ${f}\n`);
      }

      process.stdout.write(`track-files:\n`);
      if (trackFiles.length === 0) {
        process.stdout.write(`  (none)\n`);
      } else {
        for (const f of trackFiles) process.stdout.write(`  - ${f}\n`);
      }
    } catch (error) {
      printCommandError(error);
    }
  });

  const bcmd = sch
    .command("build")
    .description("Build sch-track-<track>.yaml from sch-strategy-<track>.yaml and catalogs");
  addProjectOption(bcmd);
  bcmd.requiredOption("--track <track>", "Track name (e.g. launch)");
  bcmd.option("--force", "Overwrite existing sch-track-<track>.yaml", false);
  bcmd.option("--dry-run", "Print generated YAML to stdout without writing", false);
  bcmd.action((opts) => {
    try {
      const { schedulePath, baseDir } = resolveSchedulePath(opts);
      const track = opts.track.trim();

      const strategyFile = join(schedulePath, `sch-strategy-${track}.yaml`);
      if (!existsSync(strategyFile)) {
        throw new Error(`Strategy file not found: ${strategyFile}`);
      }

      const outFile = join(schedulePath, `sch-track-${track}.yaml`);
      if (existsSync(outFile) && !opts.force && !opts.dryRun) {
        throw new Error(
          `${outFile} already exists. Use --force to overwrite or --dry-run to preview.`,
        );
      }

      const targetResult = buildScheduleTrack(strategyFile, baseDir);
      const { projectId, status, startDate, tasks, errors } = targetResult;

      for (const e of errors) process.stdout.write(`ERROR: ${e}\n`);

      if (errors.length > 0) {
        process.exitCode = 1;
        return;
      }

      const projectMilestones = collectProjectMilestones(schedulePath, baseDir, projectId, {
        strategyPath: strategyFile,
        result: targetResult,
      });
      for (const w of projectMilestones.warnings) process.stdout.write(`WARN: ${w}\n`);
      for (const e of projectMilestones.errors) process.stdout.write(`ERROR: ${e}\n`);
      if (projectMilestones.errors.length > 0) {
        process.exitCode = 1;
        return;
      }

      const outDoc = createScheduleTrackDocument({
        projectId,
        track,
        status,
        startDate,
        tasks,
      });

      const outYaml = yaml.dump(outDoc, {
        lineWidth: 120,
        quotingType: '"' as const,
        forceQuotes: false,
        noRefs: true,
      });

      if (opts.dryRun) {
        process.stdout.write(outYaml);
        process.stdout.write(`\n# dry-run: ${tasks.length} tasks — not written to disk\n`);
        updateMilestonesFile(schedulePath, projectId, projectMilestones.milestones, true);
        return;
      }

      writeFileSync(outFile, outYaml, "utf8");
      process.stdout.write(`Generated: ${outFile} (${tasks.length} tasks)\n`);

      const milestonesFile = join(schedulePath, "sch-milestones.yaml");
      if (projectMilestones.milestones.length > 0 || existsSync(milestonesFile)) {
        const { added, updated, removed, fileCreated } = updateMilestonesFile(
          schedulePath,
          projectId,
          projectMilestones.milestones,
          false,
        );
        const verb = fileCreated ? "Created" : "Updated";
        const detail = [
          ...added.map((id) => `added ${id}`),
          ...updated.map((id) => `updated ${id}`),
          ...removed.map((id: string) => `removed ${id}`),
        ].join(", ");
        process.stdout.write(`${verb}: ${milestonesFile} (${detail})\n`);
      }
    } catch (error) {
      printCommandError(error);
    }
  });

  registerScheduleAssessmentCommands(sch);
  registerScheduleStrategyCommands(sch);
}
