import { type Command } from "commander";
import { join, resolve } from "node:path";
import { existsSync, readdirSync, writeFileSync } from "node:fs";
import yaml from "js-yaml";
import { getProjectSchedulePath, loadConfig, loadEnv, specdojoRootDir } from "./specdojo-config.js";
import {
  buildScheduleTrack,
  type BuildResult,
  type GeneratedMilestone,
  type GeneratedTask,
} from "./schedule-build.js";
import { readYaml } from "./exec-shared.js";

function resolveSchedulePath(opts: { project?: string }): {
  schedulePath: string;
  baseDir: string;
} {
  loadEnv();
  const { config, configPath } = loadConfig();
  const baseDir = specdojoRootDir();

  const projectId =
    opts.project?.trim() ||
    process.env.SPECDOJO_PROJECT?.trim() ||
    (config ? Object.keys(config.projects)[0] : "");

  if (!config) {
    throw new Error(`schedule commands require specdojo.config.json.\nRun: specdojo config init`);
  }
  if (!projectId) {
    throw new Error(`No project specified. Use --project <id> or SPECDOJO_PROJECT.`);
  }

  const project = config.projects[projectId];
  if (!project) {
    throw new Error(`Unknown project: ${projectId} (check ${configPath})`);
  }

  if (!project.schedule_path?.trim()) {
    throw new Error(`schedule_path not set for project '${projectId}' in ${configPath}.`);
  }

  return { schedulePath: resolve(baseDir, getProjectSchedulePath(project)), baseDir };
}

export type ProjectMilestoneBuild = {
  milestones: GeneratedMilestone[];
  errors: string[];
  warnings: string[];
};

export function collectProjectMilestones(
  schedulePath: string,
  baseDir: string,
  projectId: string,
  prebuilt?: { strategyPath: string; result: BuildResult },
): ProjectMilestoneBuild {
  const milestones: GeneratedMilestone[] = [];
  const errors: string[] = [];
  const warnings: string[] = [];
  const owners = new Map<string, string>();
  const prebuiltPath = prebuilt ? resolve(prebuilt.strategyPath) : undefined;
  const strategyFiles = readdirSync(schedulePath)
    .filter((file) => /^sch-strategy-.+\.yaml$/.test(file))
    .sort();

  for (const file of strategyFiles) {
    const strategyPath = join(schedulePath, file);
    let result: BuildResult;
    try {
      result =
        prebuilt && prebuiltPath === resolve(strategyPath)
          ? prebuilt.result
          : buildScheduleTrack(strategyPath, baseDir);
    } catch (error) {
      errors.push(`${file}: ${error instanceof Error ? error.message : String(error)}`);
      continue;
    }

    warnings.push(...result.warnings.map((warning) => `${file}: ${warning}`));
    errors.push(...result.errors.map((error) => `${file}: ${error}`));
    if (result.errors.length > 0) continue;
    if (result.projectId !== projectId) {
      errors.push(
        `${file}: project id '${result.projectId}' does not match requested project '${projectId}'`,
      );
      continue;
    }

    for (const milestone of result.milestones) {
      const previousOwner = owners.get(milestone.id);
      if (previousOwner) {
        errors.push(
          `Duplicate milestone ID '${milestone.id}' generated by ${previousOwner} and ${file}`,
        );
        continue;
      }
      owners.set(milestone.id, file);
      milestones.push(milestone);
    }
  }

  return { milestones, errors, warnings };
}

export function updateMilestonesFile(
  schedulePath: string,
  projectId: string,
  newMilestones: GeneratedMilestone[],
  status: string,
  dryRun: boolean,
): { added: string[]; updated: string[]; removed: string[]; fileCreated: boolean } {
  const filePath = join(schedulePath, "sch-milestones.yaml");
  if (newMilestones.length === 0 && !existsSync(filePath))
    return { added: [], updated: [], removed: [], fileCreated: false };

  const added: string[] = [];
  const updated: string[] = [];
  let fileCreated = false;

  let doc: Record<string, unknown>;

  if (existsSync(filePath)) {
    const parsed = readYaml(filePath);
    if (!parsed || typeof parsed !== "object") {
      throw new Error(`${filePath}: invalid or empty YAML`);
    }
    doc = parsed as Record<string, unknown>;
    if (!Array.isArray(doc.milestones)) doc.milestones = [];
  } else {
    doc = {
      kind: "milestones",
      id: `${projectId}:sch-milestones`,
      type: "project",
      status,
      version: 1,
      project_id: projectId,
      settings: {},
      milestones: [],
    };
    fileCreated = true;
  }

  // sch-milestones.yaml is fully managed by schedule build, so its status
  // tracks the strategy status on every build (not only on creation).
  doc.status = status;

  const previous = doc.milestones as Array<Record<string, unknown>>;
  const previousIds = new Set(previous.map((entry) => String(entry?.id ?? "")));
  const newIds = new Set(newMilestones.map((m) => m.id));
  const removed: string[] = [];
  for (const entry of previous) {
    const id = String(entry?.id ?? "");
    if (!newIds.has(id)) removed.push(id);
  }

  for (const m of newMilestones) {
    if (previousIds.has(m.id)) updated.push(m.id);
    else added.push(m.id);
  }
  doc.milestones = newMilestones.map((milestone) => ({ ...milestone }));

  const outYaml = yaml.dump(doc, { lineWidth: 120, noRefs: true });

  if (dryRun) {
    const label = fileCreated ? "created" : "updated";
    process.stdout.write(`\n# --- (dry-run) sch-milestones.yaml (${label}) ---\n`);
    process.stdout.write(outYaml);
  } else {
    writeFileSync(filePath, outYaml, "utf8");
  }

  return { added, updated, removed, fileCreated };
}

function printCommandError(error: unknown): void {
  const message = error instanceof Error ? error.message : String(error);
  process.stdout.write(message + "\n");
  process.exitCode = 1;
}

function addProjectOption(cmd: Command): Command {
  return cmd.option("--project <projectId>", "Project id in specdojo.config.json");
}

export function createScheduleTrackDocument(input: {
  projectId: string;
  track: string;
  status: string;
  startDate: string | null;
  tasks: GeneratedTask[];
}): Record<string, unknown> {
  return {
    kind: "track",
    id: `${input.projectId}:sch-track-${input.track}`,
    type: "project",
    status: input.status,
    title: `スケジュールトラック（${input.track}）`,
    rulebook: "specdojo:sch-rulebook",
    version: 1,
    project_id: input.projectId,
    track: input.track,
    settings: input.startDate !== null ? { start_date: input.startDate } : {},
    tasks: input.tasks,
  };
}

export function registerScheduleCommands(program: Command): void {
  const sch = program.command("schedule").description("Schedule build commands");

  // --- where ---
  const wcmd = sch.command("where").description("Print resolved schedule paths and file list");
  addProjectOption(wcmd);
  wcmd.action((opts) => {
    try {
      const { schedulePath } = resolveSchedulePath(opts);
      process.stdout.write(`schedule-path: ${schedulePath}\n`);

      if (!existsSync(schedulePath)) {
        process.stdout.write(`(path does not exist)\n`);
        return;
      }

      const files = readdirSync(schedulePath)
        .filter((f) => /^sch-.+\.yaml$/.test(f))
        .sort();
      const strategyFiles = files.filter((f) => f.startsWith("sch-strategy-"));
      const trackFiles = files.filter((f) => f.startsWith("sch-track-"));

      process.stdout.write(`strategy-files:\n`);
      if (strategyFiles.length === 0) {
        process.stdout.write(`  (none)\n`);
      } else {
        for (const f of strategyFiles) process.stdout.write(`  - ${f}\n`);
      }

      process.stdout.write(`track-files:\n`);
      if (trackFiles.length === 0) {
        process.stdout.write(`  (none)\n`);
      } else {
        for (const f of trackFiles) process.stdout.write(`  - ${f}\n`);
      }
    } catch (error) {
      printCommandError(error);
    }
  });

  const bcmd = sch
    .command("build")
    .description("Build sch-track-<track>.yaml from sch-strategy-<track>.yaml and catalogs");
  addProjectOption(bcmd);
  bcmd.requiredOption("--track <track>", "Track name (e.g. launch)");
  bcmd.option("--force", "Overwrite existing sch-track-<track>.yaml", false);
  bcmd.option("--dry-run", "Print generated YAML to stdout without writing", false);
  bcmd.action((opts) => {
    try {
      const { schedulePath, baseDir } = resolveSchedulePath(opts);
      const track = opts.track.trim();

      const strategyFile = join(schedulePath, `sch-strategy-${track}.yaml`);
      if (!existsSync(strategyFile)) {
        throw new Error(`Strategy file not found: ${strategyFile}`);
      }

      const outFile = join(schedulePath, `sch-track-${track}.yaml`);
      if (existsSync(outFile) && !opts.force && !opts.dryRun) {
        throw new Error(
          `${outFile} already exists. Use --force to overwrite or --dry-run to preview.`,
        );
      }

      const targetResult = buildScheduleTrack(strategyFile, baseDir);
      const { projectId, status, startDate, tasks, errors } = targetResult;

      for (const e of errors) process.stdout.write(`ERROR: ${e}\n`);

      if (errors.length > 0) {
        process.exitCode = 1;
        return;
      }

      const projectMilestones = collectProjectMilestones(schedulePath, baseDir, projectId, {
        strategyPath: strategyFile,
        result: targetResult,
      });
      for (const w of projectMilestones.warnings) process.stdout.write(`WARN: ${w}\n`);
      for (const e of projectMilestones.errors) process.stdout.write(`ERROR: ${e}\n`);
      if (projectMilestones.errors.length > 0) {
        process.exitCode = 1;
        return;
      }

      const outDoc = createScheduleTrackDocument({
        projectId,
        track,
        status,
        startDate,
        tasks,
      });

      const outYaml = yaml.dump(outDoc, {
        lineWidth: 120,
        quotingType: '"' as const,
        forceQuotes: false,
        noRefs: true,
      });

      if (opts.dryRun) {
        process.stdout.write(outYaml);
        process.stdout.write(`\n# dry-run: ${tasks.length} tasks — not written to disk\n`);
        updateMilestonesFile(schedulePath, projectId, projectMilestones.milestones, status, true);
        return;
      }

      writeFileSync(outFile, outYaml, "utf8");
      process.stdout.write(`Generated: ${outFile} (${tasks.length} tasks)\n`);

      const milestonesFile = join(schedulePath, "sch-milestones.yaml");
      if (projectMilestones.milestones.length > 0 || existsSync(milestonesFile)) {
        const { added, updated, removed, fileCreated } = updateMilestonesFile(
          schedulePath,
          projectId,
          projectMilestones.milestones,
          status,
          false,
        );
        const verb = fileCreated ? "Created" : "Updated";
        const detail = [
          ...added.map((id) => `added ${id}`),
          ...updated.map((id) => `updated ${id}`),
          ...removed.map((id: string) => `removed ${id}`),
        ].join(", ");
        process.stdout.write(`${verb}: ${milestonesFile} (${detail})\n`);
      }
    } catch (error) {
      printCommandError(error);
    }
  });
}
